### PR TITLE
Refactoring: Force `ruff` static checker for project

### PR DESCRIPTION
**Pull request by penguinolog**
* do not use `assert` in production code
* package files are not executable
* use `isinstance`
* stop checks like `if boolean == True: ...`
* use `contextlib.suppress`
* explicit return `None` in optionals
* reduce amount of shadowed keywords (`next`, ...)

##### Checklist
- [X] I've ensured that similar functionality has not already been implemented
- [X] I've ensured that similar functionality has not earlier been proposed and declined
- [X] I've branched off the `master` or `python-dual-support` branch
- [X] I've merged fresh upstream into my branch recently
- [X] I've ran `tox` successfully in local environment
- [ ] I've included docstrings and/or documentation and/or examples for my code (if this is a new feature)

### CODE REVIEW

**Comment by ulidtko** [comment]
@penguinolog you should give more time for code review. 4 minutes between opening a `+755 −698` PR and insta-merging it — is not sufficient to post even a short comment.

**Comment by penguinolog** [comment]
I agree, but this PR from hell was 90% automatically generated

**Comment by ulidtko** [comment]
That's even worse.

Source code is for humans to read.

**Comment by neiljp** [comment]
It's great to see this extra linting of the project, but I'd agree re reviewing. Personally, I'd break these automated changes into multiple commits, each linting/fixing additional aspects.

**Pull request merged**
