### PR TITLE
[WIP] 24-bit (true color) support.

### PR DESCRIPTION
**Pull request by and3rson**
* Palette entires can now use 6-digit #rrggbb hex codes.
* These codes are converted to true color escape sequences for terminals that
      have the proper support.
* Documentation updates to follow.

##### Checklist
- [ ] I've ensured that similar functionality has not already been implemented
- [ ] I've ensured that similar functionality has not earlier been proposed and declined
- [ ] I've branched off the `master` or `python-dual-support` branch
- [ ] I've merged fresh upstream into my branch recently
- [ ] I've ran `tox` successfully in local environment
- [ ] I've included docstrings and/or documentation and/or examples for my code (if this is a new feature)

##### Description:
*(P. S. If this pull requests fixes an existing issue, please specify which one.)*

### CODE REVIEW

**Comment by tonycpsu** [comment]
If everything looks okay on this code-wise I'll start working on the documentation updates.

**Comment by tonycpsu** [comment]
@and3rson: any updates?  seems like urwid development has stalled in the last few months...

**Comment by and3rson** [comment]
@tonycpsu I think this is definitely something we need to have. Can you follow up about the current state of this PR? It's been a while since I last had time for it...

**Comment by and3rson** [comment]
Looks wonderful! Thank you for your work.

I will definitely review and merge this later today.

**Comment by rht** [comment]
Bump.

**Comment by tonycpsu** [comment]
@and3rson : do you still plan on merging this?  I have a project I'd like to release to PyPi soon that makes extensive use of 24-bit color.

**Comment by tonycpsu** [comment]
Seeing as [zulip-terminal](https://github.com/zulip/zulip-terminal/) and my own [streamglob](https://github.com/tonycpsu/streamglob/) are already using this functionality, and not seeing any objections to the PR in over a year, I'll go ahead and merge now.

**Pull request merged**
