### PR TITLE
Added pack method to LineBox. Fixes: #346

### PR DESCRIPTION
**Pull request by mdtrooper**
##### Checklist
- [x] I've ensured that similar functionality has not already been implemented
- [ ] I've ensured that similar functionality has not earlier been proposed and declined
- [x] I've branched off the `master` or `python-dual-support` branch
- [x] I've merged fresh upstream into my branch recently
- [x] I've ran `tox` successfully in local environment
- [x] I've included docstrings and/or documentation and/or examples for my code (if this is a new feature)

##### Description:
I fixed the bug #346

### CODE REVIEW

**Comment by d0c-s4vage** [comment]
Looks like the failed test wasn't due to the code changes, but is due to something in travis-ci https://travis-ci.org/urwid/urwid/jobs/627541475:

```
After this operation, 693 kB of additional disk space will be used.
Err:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 python-gi amd64 3.20.0-0ubuntu1
  Could not connect to build-cache.travisci.net:80 (10.80.1.2), connection timed out
Err:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 python-gi amd64 3.20.0-0ubuntu1
  Could not connect to build-cache.travisci.net:80 (10.80.1.2), connection timed out
Err:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 python-gi amd64 3.20.0-0ubuntu1
  Could not connect to build-cache.travisci.net:80 (10.80.1.2), connection timed out
Err:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 python-gi amd64 3.20.0-0ubuntu1
  Could not connect to build-cache.travisci.net:80 (10.80.1.2), connection timed out
Err:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 python-gi amd64 3.20.0-0ubuntu1
  Could not connect to build-cache.travisci.net:80 (10.80.1.2), connection timed out
Err:1 http://archive.ubuntu.com/ubuntu xenial/main amd64 python-gi amd64 3.20.0-0ubuntu1
  Could not connect to build-cache.travisci.net:80 (10.80.1.2), connection timed out
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/pygobject/python-gi_3.20.0-0ubuntu1_amd64.deb  Could not connect to build-cache.travisci.net:80 (10.80.1.2), connection timed out
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command "sudo apt-get install python-gi python3-gi" failed and exited with 100 during .
```

**Comment by mdtrooper** [comment]
How do I refresh the tests of travis? @d0c-s4vage

**Comment by ulidtko** [comment]
@mdtrooper you can do empty `git commit --amend` followed by `git push -f`. This will modify dates of your HEAD commit, and therefore change the commit sha, and so will be seen as new content by CI bots.

**Comment by mdtrooper** [comment]
> @mdtrooper you can do empty `git commit --amend` followed by `git push -f`. This will modify dates of your HEAD commit, and therefore change the commit sha, and so will be seen as new content by CI bots.

Thanks @ulidtko for the tip. Now it is green.

**Comment by tonycpsu** [comment]
LGTM.  Sorry about the delay.

**Pull request merged**
