### PR TITLE
Add a ReadlineMixin class to emulate some of readline behavior

### PR DESCRIPTION
**Pull request by sitaktif**
Here is a mixin class to add common readline shortcuts to Edit widgets.

It contains tests, doc and an example that I put in the examples/ directory. One might argue that the example is a bit too simple to be there - please give me your feedback.

I think it is compatible with the "highlights" but if I understand correctly, the latter is not working at the moment I could not really test it.

Cheers,
Sitaktif

### CODE REVIEW

**Comment by rr-** [comment]
Is this alive?

**Comment by rr-** [comment]
I made this:

https://pypi.python.org/pypi/urwid-readline/

**Comment by rr-** [comment]
I made this:

https://pypi.python.org/pypi/urwid-readline/

**Comment by tonycpsu** [comment]
urwid-readline seems to fill the underlying need here very well, and seems to be actively maintained.  @rr- , would you have interest in migrating urwid-readline into urwid proper?

**Comment by rr-** [comment]
Nope @tonycpsu  urwid development is too stale for me. 40 commits to master in 2018 alone.

**Comment by tonycpsu** [comment]
@rr- , you're not wrong, but I think you'll find that's about to change.  urwid added two new maintainers yesterday (@ulidtko and myself), and we're starting work on clearing the backlog of PRs, with the hopes of reinvigorating the project.  My thought as I was looking through the backlog was that something like urwid-readline would be a good fit as an urwid-builtin, but I certainly respect your decision.

In any event, urwid-readline is in my view a better path forward than this PR, so I'm going to close this out.  Anyone who wants readline functionality should use urwid-readline.

**Pull request closed without merging**
