### PR TITLE
Fix tutorial: rename `attr` to `urwid_attr`

### PR DESCRIPTION
**Pull request by penguinolog**
Prevent stdlib `attr` shadowing in case of `sys.path` altered

Fix: #649

##### Checklist
- [X] I've ensured that similar functionality has not already been implemented
- [X] I've ensured that similar functionality has not earlier been proposed and declined
- [X] I've branched off the `master` or `python-dual-support` branch
- [X] I've merged fresh upstream into my branch recently
- [x] I've ran `tox` successfully in local environment
- [X] I've included docstrings and/or documentation and/or examples for my code (if this is a new feature)

### CODE REVIEW

**Comment by penguinolog** [comment]
@mwhudson without this PR changes, full regeneration of images in documentation is impossible :-(

**Review by wardi — APPROVED** [review]
interesting, is there something special about the name attr?

**Comment by penguinolog** [comment]
> interesting, is there something special about the name attr?

I mixed in my memory dataclasses with "attrs" package.
`attr` is a part of `attrs` package, it is extremely common library for cases, where dataclasses are not available or not enough functional.
You define like 
```python

import attr

@attr.s
class Config:
    a: dict[str, int] = attr.ib(factory=dict, ...
```
And other code is generated

**Comment by wardi** [comment]
so this change isn't actually required then

**Comment by penguinolog** [comment]
> so this change isn't actually required then

Scripts location is added to `sys.path` at first position, then during imports modules lookup uses `sys.path`. Anything using `attr` is broken and it's one of our dependencies, which call some logic on import

**Comment by wardi** [comment]
the docs/tutorial directory isn't added to sys.path and these are scripts not modules to be imported, right?

**Comment by penguinolog** [comment]
> the docs/tutorial directory isn't added to sys.path and these are scripts not modules to be imported, right?

It's added automatically on run as script.
Short example
```
alekseis@1857be7-lcelt ~/tmp $ batcat *          
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: logging.py
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ print("this should not be executed")
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: tst.py
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ import logging
   2   │ import sys
   3   │ 
   4   │ print(sys.path)
   5   │ 
   6   │ logging.basicConfig(level=logging.INFO)
   7   │ logger = logging.getLogger(__name__)
   8   │ logger.info("it works")
───────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
alekseis@1857be7-lcelt ~/tmp $ python tst.py     
this should not be executed
['/home/alekseis/tmp', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/usr/local/lib/python3.11/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.11/dist-packages']
Traceback (most recent call last):
  File "/home/alekseis/tmp/tst.py", line 6, in <module>
    logging.basicConfig(level=logging.INFO)
    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute 'basicConfig'
```
As you can see, `sys.path` was altered and instead of normal logging, another code was imported

**Pull request merged**
