### PR TITLE
Allow Screen class to set signal handlers using a function provided by the event loop

### PR DESCRIPTION
**Pull request by federicotdn**
##### Checklist
- [x] I've ensured that similar functionality has not already been implemented
- [x] I've ensured that similar functionality has not earlier been proposed and declined
- [x] I've branched off the `master` or `python-dual-support` branch
- [x] I've merged fresh upstream into my branch recently
- [x] I've ran `tox` successfully in local environment
- [x] I've included docstrings and/or documentation and/or examples for my code (if this is a new feature)

##### Description:
The Screen class used to set signal handlers using the `signal()` function
from the `signal` standard library module.  This commit changes this
behaviour so that the Screen class now uses a function provided by the active
event loop to set signal event handlers.  This allows us to use GLib
specific signal handling functions when using the GLib event loop.

This PR fixes the second example of issue https://github.com/urwid/urwid/issues/267.

Note: Although the SIGWINCH signal will now by handled correctly, the SIGCONT signal will not be monitored, as the GLib [g_unix_signal_source_new() function](https://developer.gnome.org/glib/stable/glib-UNIX-specific-utilities-and-integration.html#g-unix-signal-source-new) only allows certain signals to be monitored. This is a limitation of GLib.

### CODE REVIEW

**Comment by federicotdn** [comment]
@and3rson would it be possible to re-run the Travis build? It looks like a test from `TwistedEventLoopTest` failed, and only on Python 3.3, so it doesn't sound like it's related to what I've modified.

**Comment by and3rson** [comment]
This looks interesting. Can you provide a specific example use case for this feature?

**Comment by and3rson** [comment]
Sorry, didn't see the github issue. Makes sense now.

**Comment by and3rson** [comment]
Ideally we should move everything related to signals into main loop classes, but that requires too much refactoring, so this PR is all we need now.
Thanks!

**Comment by federicotdn** [comment]
@and3rson what we have at the moment is a `MainLoop` class, which has two properties: `event_loop`, which can be an instance of `SelectEventLoop`, `GLibEventLoop`, etc. and `screen`, which can be an instance of `raw_display.Screen`, `curses_display.Screen`, `web_display.Screen`, etc.  The `event_loop` and `screen` properties do not have references to each other, and neither do they have references to the `MainLoop` who instanced them.

The problem with this was that a specific `Screen` class (`raw_display`) needed special signal handling when running with a specific event loop (`GLibEventLoop`), so at the end, this `Screen` class needed to be aware of how this event loop wanted to handle UNIX signals.  So my solution was to specify the desired signal handler setter function (such as `signal.signal()`) in each `EventLoop` class, and then pass it to the `screen` property, but only if `screen` is an instance of `raw_display.Screen`, since the other `Screen` classes to not use signals (this was done using `hasattr()`, which is ugly).

**Comment by and3rson** [comment]
@federicotdn thanks for the clarification. Makes perfect sense.

**Comment by and3rson** [comment]
Do you mind adding some docs for this as well to make devs aware of using this feature?

**Comment by federicotdn** [comment]
@and3rson sure, no problem.

**Pull request merged**
