### PR TITLE
Add 'linefocus' option to Columns class

### PR DESCRIPTION
**Pull request by rndusr**
This makes it possible to render a whole line as focused with different display attributes for each widget.

### CODE REVIEW

**Comment by topisani** [comment]
+1. Id be really happy for this one!

**Comment by wardi** [comment]
if you're trying to highlight a whole row just wrap your columns with an AttrMap instead of putting the AttrMap inside each column

**Comment by rndusr** [comment]
But that doesn't work if I want the widgets in the Columns to have different
display attributes.

Take this file list for example:

    File name    File size
    foo.jpg      421kB
    bar.txt        2kB

I want the name to be dark blue on black and the size to be dark green on
black. Focused lines are light blue on dark gray and light green on dark gray.

**Comment by wardi** [comment]
sure it does.

```python
AttrMap(
    Columns([
        AttrMap(Text('foo.jpg'), 'filename'),
        AttrMap(Text('421kB'), 'filesize')]),
    None,
    {'filename': 'filename-focus', 'filesize': 'filesize-focus'})
```

**Comment by rndusr** [comment]
Oh. Okay. I'll try that.
Thanks for your help.

**Pull request closed without merging**
