### PR TITLE
Mention blink and italics attributes in manual.

### PR DESCRIPTION
**Pull request by geier**

### CODE REVIEW

**Comment by geier** [comment]
If someone wants to try it, [here is a little script to test blink and italics](https://gist.github.com/geier/4313dd83cb6bb04b98b8c5c2db8ebc6f).

Also, I'd love to add strikethrough to that list [hint](https://github.com/urwid/urwid/pull/239) :smiling_imp: .

**Comment by geier** [comment]
For the record, I don't believe the test failure has anything to with this PR.

**Comment by and3rson** [comment]
Nice catch, thanks!

**Comment by and3rson** [comment]
The builds are fixed now.

**Pull request merged**
