### PR TITLE
Add support for keys 'home' and 'end' to ListBox

### PR DESCRIPTION
**Pull request by rndusr**
Pressing 'home' moves the focus to the first position, 'end' moves focus to the
last position.

### CODE REVIEW

**Comment by and3rson** [comment]
Hi! Thanks for the contribution.

We're now trying to keep urwid alive and are reviewing all open pull requests.

I've recently fixed the build process. In order to properly re-run the build, can you please update your forked repo branch with fresh base upstream to run the build within the latest codebase?

Thanks!

**Comment by and3rson** [comment]
@rndusr Did you merge master in? The diff looks pretty weird.

**Comment by rndusr** [comment]
Yes. That's how I understood "update your forked repo branch with fresh base upstream".

What was I supposed to do?

I'm a bit busy the next few days, but I'll fix it eventually.

**Comment by and3rson** [comment]
Seems like GitHub uses outdated target branch for this pull request. I'll reopen a new one.

**Comment by and3rson** [comment]
See #269.

**Pull request closed without merging**
